### ISSUE TITLE
Add option for single-pass word-by-word processing to enable continous listening to commands

### ISSUE THREAD

**Issue by omlins** [ideasman42/nerd-dictation#16]
It would be nice to have an option for single-pass word-by-word processing (or similar) in order to enable continuous listening to commands **without emitting them multiple times** (c.f. #17).

To avoid undesired behavior in continuous listening the option to Add '--commands' command line argument to restrict input to a limited set of commands (#3) could also be a solution here.

**Comment by omlins** [comment]
@ideasman42 , does this make sense to you? Would that be difficult to add? 

(...and thanks for having brought this awesome project to the world!)

**Comment by ideasman42** [comment]
This would be great to support, although I think this could be handled in the user configuration - with some minor extension.

The way VOSK works, words may be modified as you talk (based on statistics of likely word choice).

For typing that's OK since words can be back spaced and typed in again, however it doesn't work for commands.

There would need to be away for:
- Commands to be executed immediately, ignoring any updates from VOSK's statistical model.
- The user configuration to return user input such as mouse buttons (not so difficult).

**Comment by omlins** [comment]
> I'm not keen on adding too much specific functionality, there is value in keeping this small and simple allowing users to hack their own configurations to add extended functionality.

Thanks for your reply! I totally share this philosophy of keeping things simple and having few, but powerful features.

I will soon come back with a solution draft in form of an update in the PR #17...
