### ISSUE TITLE
Mostly thanks!

### ISSUE THREAD

**Issue by saif-ellafi** [ideasman42/nerd-dictation#30]
I am aware this is not the right place for that, but wanted to reach out just to say thanks for creating this project!
Only on Windows 11 is the Voice Dictation tool universally available to write anywhere.

As a hobby, I do some writing and this is exactly what I was looking for.

Just as an anecdote, I am using the following changes to support for some basic keyboard commands

```
    text = text.replace(" new line", "\n")
    text = text.replace(" dash", "-")
    text = text.replace(" slash", "/")
    text = text.replace(" period", ".")
    text = text.replace(" comma", ",")
    text = text.replace(" coma", ",") # This is probably because of my accent, serves as an example too
    text = text.replace(" calmer", ",") # This is probably because of my accent, serves as an example too
    text = text.replace(" colon", ":")
    text = text.replace(" question mark", "?")
    text = text.replace(" exclamation mark", "!")
```
I had to take care a bit of my microphone's input quality, but could do with Pipewire + Easy Effects, to deal with noise suppression and the such, but afterwards, the english standard models works more than fine with this.

Best regards and take care!

**Comment by ideasman42** [comment]
Hi, glad you find this useful.

I'd rather keep these kind of replacement tables part of the user configuration.

If you would like to add an example configuration, that can be done here:

https://github.com/ideasman42/nerd-dictation/tree/master/examples

It could be called `quoted_characters` for e.g.

Also, it would be cleaner to use a variable:

```
REPLACE_PUNCTUATION_LITERALS = (
    ("new line", "\n"),
    ("dash", "-")
    # ... etc ...
)
# --- snip ---
    for src, dst in REPLACE_PUNCTUATION_LITERALS:
        text = text.replace(src, dst)
``` 

Also, the space at the start wont work if someone starts saying so regex could be used to detect word boundaries, or - you could do some trick with Python's string manipulation to support this.

Closing since this isn't an issue to resolve, I would accept a PR that adds an example though.
