### ISSUE TITLE
Large model surrounding sentences with 'the'

### ISSUE THREAD

**Issue by saif-ellafi** [ideasman42/nerd-dictation#31]
Not sure why, but all of my sentences when using the large english model, appear as if delimited with the word 'the'

`the that is a success the`

**Comment by ideasman42** [comment]
@saif-ellafi strange, I've never had this happen. Could you double check this happens with a blank/no configuration?

Besides this - not sure what can be done on my side.

**Comment by saif-ellafi** [comment]
It happens just with
`./nerd-dictation begin --vosk-model-dir=./model_en_us`
given this model is `vosk-model-en-us-0.22.zip`

**Comment by xenotropic** [comment]
I'd say this should be closed for nerd-dictation since it's a vosk model problem. The main model for vosk is also slooow to start for me, like ten seconds or so. The vosk-model-en-us-daanzu-20200905 model seems to solve both these issues. Haven't used the daanzu much but it just 100%'ed the first sentence of the declaration of independence which seems pretty impressive to me.

**Comment by ideasman42** [comment]
Closing as this is an issue with the model, it could be handled by documentation.
