### ISSUE TITLE
Is using nerd-dictation to control software a solved problem?

### ISSUE THREAD

**Issue by matkoniecz** [ideasman42/nerd-dictation#36]
I want to use nerd-dictation for processing my photos, basically:

- show photo
- wait for command (`next` `previous` `delete` `promote`)
- if command is detected: show what was detected (or produce sound feedback?), execute action

I am not entirely sure what would be the best way to implement this - has anyone did something like that already? Seems a relatively obvious use of actually working voice-to-text.

(maybe using `nerd-dictation` is a mistake and I should be using vosk API directly?)

**Comment by ideasman42** [comment]
This seems like a good use for nerd-dictation, and there is no need for you to use VOSK directly (unless you really want to for some reason).

One thing that would be useful in this case is a way to specify a custom configuration file, so special use-cases could define their own commands.

This can be added without much trouble, for now though you could try using a user-configuration to detect words and act on them.

**Comment by matkoniecz** [comment]
So https://github.com/ideasman42/nerd-dictation/blob/master/examples/begin_end_commands/nerd-dictation.py would be likely a good base, right?

**Comment by ideasman42** [comment]
If you wanted, the begin/end logic is more advanced then you need - so you could start there but strip it down a lot.

**Comment by ideasman42** [comment]
Added "--config" option cfcaf90eb0bc953840b904bcead6aaedac392a44, so you can have special purpose configurations (such as the one you have described).

**Comment by omlins** [comment]
@matkoniecz : I have made a large effort to address this issue seriously (discussed first in the issue #19  that I have opened have a year ago). Looking through the source code of nerd-dictation, I figured out that it currently does not do anything that would help for a secure, low latency speech to command translation (besides, the few comments of @ideasman42 on this subject, since I have opened the issue half a year ago, have shown that he was not interested in development in that direction - which is totally fine: his repo - his vision!). As a result, I have created JustSayIt, which enables secure, low latency speech to command translation and is usable as software or API. It implements a novel algorithm for high performance context dependent recognition of spoken commands. Here you can find out more:
https://github.com/omlins/JustSayIt.jl

**Comment by ideasman42** [comment]
Closing this report as I don't think it helps to keep it open.

nerd dictation may have features added at some point which assist with this workflow, however the primary use-case is still dictation.
