### ISSUE TITLE
Capitalize words arbitrarily with preceding command / escape word

### ISSUE THREAD

**Issue by xenotropic** [ideasman42/nerd-dictation#40]
This is a feature request. In Dragon, one can capitalize any word by saying "cap" before it, so saying "cap nerd cap diction" outputs "Nerd Dictation". It would be nice to have this functionality in nerd-dictation. 

It would also be nice if the command word was configurable. Although "cap" was short and intuitive, it really wasn't the best choice since it is a word one actually uses fairly often.

**Comment by xenotropic** [comment]
Did this myself, just cramming some replacement functions into the list of regexes in TEXT_REPLACE_REGEX in the config file. 

[see this gist](https://gist.github.com/xenotropic/d1ccab53e0bba34f280c93955958afbd). Also has various punctuation replacements I find useful. Feel free to incorporate into main or LMK if you want me to do pull request

**Comment by ideasman42** [comment]
Thanks for providing the example.

In general I'm wary of mixing commands with natural speech the since it will confuse the statistical model (without deeper integration that excludes those words and treats them separately - which is possible but not trivial).

Without digging deep into this it might be necessary to run two recognizes at once, one that only handles single words, another that handles continuous speech, this way keywords could be detected and excluded from the continuous speech recognizer.

Nevertheless, I can see in for fully hands-free dictation it could be useful, so I may check on including this as an example configuration.

**Comment by xenotropic** [comment]
I've been using the config in the Gist the last few days to write emails and  comment on documents, and it works. I'm not sure what exactly the bad stuff from a model being "confused" would be. For the most part I don't think we're dealing with dynamic models (i.e., continuously learning from input) here that would be learning the "wrong" thing, and even if they were, well, that's what the particular user does so it would be the right thing to learn. 

So long as one chooses a multi-syllable keyword that is easily distinguishable ("capitalize" or "full stop" work well) such that the model can recognize it even in a strange context, it works. I *am* having trouble with "comma", there's just too many words around it ("karma", "come on" etc) that the model can't get it out of context, which I've noted in the Gist. Will have to think of some other distinct-but-memorable keyword(s) for that.

You may not want to make it the default config -- and of course it's your repo and do whatever you want -- but  my thought would be pointing to the Gist in the documentation as an experimental possibility. I certainly find nerd-dictation better / more useful with the capitalization and punctuation capabilities and haven't really experienced any negative effects (yet!).
