### ISSUE TITLE
Feature Request: Phoneme Output

### ISSUE THREAD

**Issue by klei22** [ideasman42/nerd-dictation#46]
Curious to look at phoneme data from input speech, would this be part of the speech-to-text pipeline, if so would there be a part of the program I could look to to modify and provide this output?

**Comment by ideasman42** [comment]
This seems like something the VOSK-SDK could support (if it doesn't already), I think if your doing lower level operations you would be better off interfacing directly with VOSK or Kaldi as nerd-dictation is using a high level API which (as far as I know) aims to avoid getting too much into the details of the dictation model. Closing since this is outside the scope the project and something which would be better handled by https://alphacephei.com/vosk/
